# Generated by Django 5.1.5 on 2025-02-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='es_administrador',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='es_normal',
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_personalizado_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_personalizado_permissions', to='auth.permission'),
        ),
    ]
