# Generated by Django 5.1.6 on 2025-02-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='validaciones_profesionales/'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
